name: qm-service

services:
  postgres_db:
    image: postgres:18.3-alpine
    command: postgres -c max_connections=500
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./.docker-initdb/restore.sh:/docker-entrypoint-initdb.d/01-restore.sh
      - ./.docker-initdb/keycloak-init.sql.gz:/tmp/backups/02-keycloak-init.sql.gz
      - ./.docker-initdb/init-db.sql:/docker-entrypoint-initdb.d/03-init.sql
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d book_db" ]
      interval: 10s
      timeout: 5s
      retries: 50
      start_period: 10s
    networks:
      - app-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.0
    container_name: keycloak
    command: start-dev
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres_db:5432/postgres
      - KC_DB_USERNAME=user
      - KC_DB_PASSWORD=password
      - KC_HOSTNAME_STRICT=false
      - KC_HTTP_ENABLED=true
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_HTTP_MANAGEMENT_PORT=9000
      - KC_HEALTH_ENABLED=true
      - KC_HOSTNAME_URL=http://localhost/auth
      - KC_HOSTNAME=localhost
      - KC_PROXY=edge
      - KC_HTTP_RELATIVE_PATH=/auth
      - KC_PROXY_HEADERS=xforwarded
    ports:
      - "8186:8080"
      - "9000:9000"
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/9000 && echo -e 'GET /auth/health/live HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\n\r\n' >&3 && cat <&3 | grep 'HTTP/1.1 200 OK' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 50
      start_period: 10s
    depends_on:
      postgres_db:
        condition: service_healthy
    networks:
      - app-network

  redis_cache:
    image: redis:8.6.2-alpine
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    image: api-gateway:1.0-SNAPSHOT
    container_name: api-gateway
    env_file:
      - .env.example
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
    depends_on:
      redis_cache:
        condition: service_started
      keycloak:
        condition: service_healthy
      book-service:
        condition: service_started
    networks:
      - app-network

  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    image: eureka-server:1.0-SNAPSHOT
    healthcheck:
      test: [ "CMD-SHELL", "netstat -an | grep 8761 | grep LISTEN || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 50
      start_period: 10s
    container_name: eureka-server
    env_file:
      - .env.example
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8761:8761"
    networks:
      - app-network

  book-service:
    build:
      context: ./book-service
      dockerfile: Dockerfile
    image: book-service:1.0-SNAPSHOT
    container_name: book-service
    env_file:
      - .env.example
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8090:8090"
    depends_on:
      postgres_db:
        condition: service_healthy
    networks:
      - app-network

  library-service:
    build:
      context: ./library-service
      dockerfile: Dockerfile
    image: library-service:1.0-SNAPSHOT
    container_name: library-service
    ports:
      - "8100:8100"
    env_file:
      - .env.example
    environment:
      - QUARKUS_PROFILE=docker
    depends_on:
      postgres_db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    networks:
      - app-network

  next-app:
    build:
      context: ./next-app
      dockerfile: Dockerfile
    image: next-app:1.0-SNAPSHOT
    container_name: next-app
    ports:
      - "3000:3000"
    env_file:
      - ./next-app/.env.example
    networks:
      - app-network

  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./.nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - next-app
      - api-gateway
    networks:
      - app-network

  comment-service:
    build:
      context: ./comment-service
      dockerfile: Dockerfile
    image: comment-service:1.0-SNAPSHOT
    container_name: comment-service
    ports:
      - '3010:3010'
    depends_on:
      - mongodb
      - eureka-server
    env_file:
      - .env.example
    environment:
      PORT: 3010
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
  mongo_data: