app:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS}

server:
  port: 8080
  netty:
    worker-threads: 4
    acceptors: 1
    connection-timeout: 3s
    max-keep-alive-requests: 1000
  http2:
    enabled: true
  forward-headers-strategy: framework

spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
      timeout: 2s
      connect-timeout: 2s
      lettuce:
        pool:
          enabled: true
          max-active: 200
          max-wait: 500ms
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          realm-client-id: ${REALM_CLIENT_ID}
          jwk-set-uri: ${JWK_SET_URI}
          issuer-uri: ${ISSUER_URI}
  codec:
    max-in-memory-size: 256KB
  cloud:
    refresh:
      enabled: false
    gateway:
      httpclient:
        connect-timeout: 300
        response-timeout: 1s
        pool:
          max-connections: 400
          acquire-timeout: 2000
          max-idle-time: 30s
          max-life-time: 120s
        compression: false
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      server:
        webflux:
          routes:
            - id: book-service-route
              uri: lb://BOOK-SERVICE
              predicates:
                - Path=/book/**
              filters:
                - TokenRelay=
                - StripPrefix=1
            - id: library-service-route
              uri: lb://LIBRARY-SERVICE
              predicates:
                - Path=/public/library/**
              filters:
                - StripPrefix=2
          default-filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@ipKeyResolver}"
            - name: Retry
              args:
                retries: 1
                statuses: BAD_GATEWAY, SERVICE_UNAVAILABLE, GATEWAY_TIMEOUT
                methods: GET, HEAD
                backoff:
                  firstBackoff: 50ms
                  maxBackoff: 250ms
                  factor: 2
            - name: CircuitBreaker
              args:
                name: defaultCB
                fallbackUri: forward:/fallback
            - RemoveRequestHeader=Cookie

resilience4j:
  circuitbreaker:
    instances:
      defaultCB:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 200
        minimumNumberOfCalls: 100
        failureRateThreshold: 50
        slowCallDurationThreshold: 1s
        slowCallRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 5

  timelimiter:
    instances:
      defaultCB:
        timeoutDuration: 2s
        cancelRunningFuture: true

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus, gateway, circuitbreakers
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}


eureka:
  client:
    healthcheck:
      enabled: false
    service-url:
      defaultZone: ${EUREKA_HOST}/eureka/
    register-with-eureka: false
    fetch-registry: true
    registry-fetch-interval-seconds: 5

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{X-Correlation-Id:-}]"
  level:
    root: INFO